name: wotlk xp preparation build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - run: |
             git config --global user.name  ${{ secrets.USERNAME }}
             git config --global user.email ${{ secrets.EMAIL }}
             git checkout --orphan gh-pages
             npm install
             npm run build
             git --work-tree dist add --all
             git --work-tree dist commit -m "new build"
             git push origin HEAD:gh-pages --force
             rm -r dist